In [ ]:
from Bio import SeqIO

filename = r"C:....\rna.fna"

results = []

for record in SeqIO.parse(filename, "fasta"):
    seq = record.seq
    results.append({
        "ID": record.id,
        "Length": len(seq),
        "A": seq.count("A"),
        "T": seq.count("T"),
        "G": seq.count("G"),
        "C": seq.count("C"),
        "N": seq.count("N"),
    })

In [5]:
import pandas as pd 
df = pd.DataFrame(results)
df

                 ID  Length     A     T     G     C  N
0    NM_001407571.1    7152  2375  1771  1618  1388  0
1    NM_001407581.1    7154  2393  1775  1596  1390  0
2    NM_001407582.1    7243  2413  1791  1634  1405  0
3    NM_001407583.1    7685  2533  1868  1783  1501  0
4    NM_001407585.1    7138  2388  1771  1592  1387  0
..              ...     ...   ...   ...   ...   ... ..
363     NM_007294.4    7088  2368  1759  1585  1376  0
364     NM_007297.4    7028  2349  1743  1572  1364  0
365     NM_007298.4    3865  1172   969   912   812  0
366     NM_007299.4    3696  1133   930   851   782  0
367     NM_007300.4    7151  2392  1775  1595  1389  0

[368 rows x 7 columns]

In [3]:
df["GC%"]= (df["G"] + df["C"]) / df["Length"] * 100
df

                 ID  Length     A     T     G     C        GC%
0    NM_001407571.1    7152  2375  1771  1618  1388  42.030201
1    NM_001407581.1    7154  2393  1775  1596  1390  41.738887
2    NM_001407582.1    7243  2413  1791  1634  1405  41.957752
3    NM_001407583.1    7685  2533  1868  1783  1501  42.732596
4    NM_001407585.1    7138  2388  1771  1592  1387  41.734379
..              ...     ...   ...   ...   ...   ...        ...
363     NM_007294.4    7088  2368  1759  1585  1376  41.774831
364     NM_007297.4    7028  2349  1743  1572  1364  41.775754
365     NM_007298.4    3865  1172   969   912   812  44.605433
366     NM_007299.4    3696  1133   930   851   782  44.182900
367     NM_007300.4    7151  2392  1775  1595  1389  41.728430

[368 rows x 7 columns]

In [ ]:
df.to_csv(
    r"C:....\BRCA1_transcri_analysis.csv"
)